### ISSUE TITLE
Something wrong with inline code

### ISSUE THREAD

**Issue by Hartrik** [abcBHM/MD2odt#4]
See example.md / HTML / Entities
```
Inside inline code: `&copy; &para; &euro; &ncaron;`.
```

The first '&' is out of code span.

**Comment by BalounJ** [comment]
Problem was in high-level API `replaceWith` method. When a *text to replace starts on index 0* in a `span` then *the replacement is outside of a parent span*.  Rewritten in **[Odt] reEscapeAll rewritten using low-lewel** commit.
